name: dart_web_audio
description: A thin wrap over JS audio APIs for Dart/Flutter. This is used by the audioplayers package to provie support for Flutter Web.
version: 0.1.1
homepage: https://github.com/luanpotter/dart_web_audio

dependencies:
  js: ^0.6.0

environment:
  sdk: ">=2.6.0 <3.0.0"

