name: dart_web_audio
description: A thin wrap over JS audio APIs for Dart/Flutter. This is used by the audioplayers package to provie support for Flutter Web.
version: 0.1.2
homepage: https://github.com/luanpotter/dart_web_audio

dependencies:
  js: ^0.6.0

dev_dependencies:
  http: ^0.12.0+4 # used in the example

environment:
  sdk: ">=2.6.0 <3.0.0"

